### PR TITLE
Alessandro patch 2024 12

### PR DESCRIPTION
**Pull request by alessandro-ramos**

### CODE REVIEW

**Comment by coreybutler** [comment]
I don't know why you thought this project was discontinued. It most certainly is not. There's a big new release later today and a big announcement coming.

**Comment by alessandro-ramos** [comment]
I'm sorry by the mistake. But your README.md says  at this time: "Notice: We have started full time work on [Runtime](https://github.com/coreybutler/nvm-windows/wiki/Runtime), the successor to NVM for Windows."

Reading this note from many months ago and looking your latest release is from November, 2023 (more than one year ago) I thought it was abbandoned. These were the evidences.

As you are saying that you have news, I am happy for you. Because its a big work to be discontinued.

Wish you all success man. Have a nice 2025. And thanks for all nice work you shared. I forwarded hundreds of developers here to download your tool.

**Comment by coreybutler** [comment]
It's true there is a successor coming, but I didn't mention discontinuing the project. Release frequency (or lack thereof) is not a good indicator of abandonment for tools like this. Stable software doesn't usually need as many releases. Granted, in this case, the delay has been due to code signing certificates. They are expensive, nobody sponsors this project, and our 3yr cert expired. I worked with Microsoft to setup an affordable new signing process, but it took significant time. In general, I'd suggest using issues/discussions/comments as a better indicator of how active a project is. The evidence is there, you just have to dig a little deeper (you can see merged PRs within the last few weeks). 

Runtime will do everything NVM4W does and far more (like [this](https://x.com/goldglovecb/status/1866967111668809949)). Eventually I'll shut down NVM4W, but not until users have adopted the new version manager.

**Comment by coreybutler** [comment]
and thank you (sincerely)... it's nice to know the project means enough to someone to carry on if I'm not able to.

**Pull request closed without merging**
