### PR TITLE
Add support for mklink with junctions

### PR DESCRIPTION
**Pull request by mklemarczyk**
Additional mode of work with support for NTFS junction points. It allows user to create link between directories when permission to create directory symlinks is denied. Fixes bug #79 

To enable the option simply put the configuration in your nvm settings.txt. (option is disabled by default to keep the compatibility.
```txt
symlink_junction: true
```

Please review well the PR, it is my first time with golang ;)
Developed with golang 1.22.3 in mind.
Tested and verified on the restricted machine. 🆗 
Tested and verified on the unrestricted machine. 🆗

### CODE REVIEW

**Comment by coreybutler** [comment]
While I appreciate the effort, see my comments on the issues related to junctions. I really hate turning away a PR and the passion you've shown for this feature and the project as a whole. I truly, truly appreciate that.

**Comment by mklemarczyk** [comment]
I will create own fork than and release there.

**Comment by mklemarczyk** [comment]
So now we can merge since there is new major version ?

**Comment by coreybutler** [comment]
First, there is only a new minor version (1.2.x), not a new major version. 

This feature will never be included in NVM4W because we are transitioning to this project's successor, [Runtime](https://github.com/coreybutler/nvm-windows/wiki/Runtime). Runtime leverages shims, so there will no longer be a need for symlinks at all. I've written a little bit about the succession plan [here](https://opensource.author.io/nvm-for-windows-v120).

**Pull request closed without merging**
