### PR TITLE
add node_mirror and npm_mirror

### PR DESCRIPTION
**Pull request by lijie371**
for chinese people, github often blocked by gfw sometime, so i add node/npm mirror options to the program, add next code to settings.txt to switch to taobao mirrors.
```
node_mirror:http://npm.taobao.org/mirrors/node/
npm_mirror:http://npm.taobao.org/mirrors/npm/
```
secondly, nodeversions.json need refresh by some program on cloud and we(i mean chinese guys) offten can't fetch that file,so i modify the method by another way.

by the way, i'm golang newbie... so, feel free to point out my mistake.

### CODE REVIEW

**Comment by coreybutler** [comment]
I just merged another PR that replaces the nodeversions.json with the new release feed from Node. I don't have the ability to test in China. Would you be willing to re-test your changes to make sure it still works? If so, I will merge this. I know using mirrors outside of the US has been painful and I'd love to get this included.

**Comment by lijie371** [comment]
it works well after i merge the newest commit

**Comment by coreybutler** [comment]
@lijie371 - Thank you. I've reviewed the code, and I don't see anything that alarms me. I'll merge this, but it may still be a few days before I can get the new installer built (I'm trying to merge multiple PR's before pushing a new release).

Thank you for doing this. I know there will be many users excited by this.

**Comment by lijie371** [comment]
You are welcome, i'm happy to do sth to make this great tool more powerful, and lots of thanks to u for sharing this tool with us.it's the best node version manager in windows i'd even used.

**Comment by Volune** [comment]
Thanks for the PR, very helpful.

Some feedback: I only managed to use the mirrors by editing the settings.txt manually. the environment variable didn't seem to be used. And the commands "nvm npm_mirror" and "nvm node_mirror" (described in "nvm help") don't seem to be implemented.

Tested successfully with:
```
node_mirror: https://npm.taobao.org/mirrors/node/
npm_mirror: https://npm.taobao.org/mirrors/npm/
```

**Comment by CrazyBBer** [comment]
no  code implemention  with command  "nvm npm_mirror" and "nvm node_mirror" in "nvm help".

**Pull request merged**
