### PR TITLE
Fixed for Node.js v4 and above

### PR DESCRIPTION
**Pull request by ghostoy**

### CODE REVIEW

**Comment by coreybutler** [comment]
Why did you strip out the `update` command?

**Comment by ghostoy** [comment]
`update` command was commented out. So I stripped it out. If you don't like, I can revert it.

**Comment by jsheely** [comment]
+1

Would be nice to get this into a release sooner rather than later. v4 is important to test against.

**Comment by midknight41** [comment]
+1

**Comment by akshah123** [comment]
why does the whole file show as if its changed?  Is that due to a different end of line character or a different tabbing format?

**Comment by ghostoy** [comment]
@akshah123 I've changed the line ends to Linux. See 7625b8c

**Pull request closed without merging**
