### PR TITLE
silent setup

### PR DESCRIPTION
**Pull request by Zougi**
- silent install without prompt as it's expected when we install nvm-windows from a script
- silent uninstall
- fix a warning (Warning: Line 80, Column 10: [Hint] Variable 'Result' never used)

### CODE REVIEW

**Comment by Zougi** [comment]
should fix https://github.com/coreybutler/nvm-windows/issues/210 and https://github.com/coreybutler/nvm-windows/issues/17

**Comment by Zougi** [comment]
on my first commit	2f27f4f I used WizardSilent and UninstallSilent variables to detect if nvm setup is in silent mode in order to suppress the message boxes. In the second commit 40d9063 I replaced MsgBox function with SuppressibleMsgBox which is better suited I believe. Indeed the code is simpler and it follows better the inno setup philosophy. use nvm-setup.exe /SILENT /SUPPRESSMSGBOXES to execute the setup without being prompted with message boxes

**Comment by Zougi** [comment]
Hi @coreybutler I believe this PR is easy to test & review, what do you think? would you integrate it?

**Comment by coreybutler** [comment]
I'm sorry for the delayed response... I had a very intense client project over the last few weeks. 

At first glance, I am not opposed to merging this, but I would like to run a few tests myself. I really appreciate what you've done... not many people dive into the installer. I'll review this in more detail as soon as I can.

**Comment by Inveracity** [comment]
This would be lovely to have, commenting to bring attention to this 🏓

**Comment by Zougi** [comment]
Yup, I was tired to wait I bought a mac. I'm only half joking, I'm on mac now.

**Review by cmego95 — APPROVED** [review]

**Pull request merged**
