### PR TITLE
Fix missing DisplayVersion registry key for nvm.iss

### PR DESCRIPTION
**Pull request by awdr74100**
winget uses the **DisplayVersion** registry key to confirm whether the package should be updated:

螢幕擷取畫面 2022-05-04 190542

winget will display the correct version:

螢幕擷取畫面 2022-05-04 190823

this avoids the problem of constant updates caused by **Unknown** versions.

refer to this [discussion](https://github.com/microsoft/winget-pkgs/issues/57635).

### CODE REVIEW

**Comment by jmichalek-fp** [comment]
This would be nice to have it merged and released so it is not constantly updated by winget

**Review by SonnyRR — APPROVED** [review]

**Review by jmichalek-fp — APPROVED** [review]

**Comment by jmichalek-fp** [comment]
@coreybutler Sorry for mentioning, would it be possible to include it in next release, please?

**Comment by balbertho** [comment]
I don't think this maybe the fix, since the DisplayVersion should be able to be set by Inno Setup in
https://github.com/jrsoftware/issrc/blob/bd96b87f5edc0317134e3d5c0b9ed321e3f01015/Projects/Install.pas#L692
Furthermore, the DisplayVersion is able to be shown before 1.1.8 release. 
What I found is that MyAppVersion is defined in https://github.com/coreybutler/nvm-windows/blob/e050a107363af310edace07ba76d0bd863f42b00/nvm.iss#L4, but it has not been used in the same file, while older release like https://github.com/coreybutler/nvm-windows/blob/1.1.7/nvm.iss will use MyAppVersion in the same file, is it maybe just a typo issue?

**Review by coreybutler — APPROVED** [review]
lgtm

**Comment by balbertho** [comment]
@coreybutler really not a typo issue? 😂

**Comment by coreybutler** [comment]
@balbertho I merged because the separation of variables for the app ID was more consistent with the rest of the installer. The typo is an easy fix.

**Comment by balbertho** [comment]
@coreybutler oh, I am sorry, I just think that no need to write the custom registry when the installer do, not noticing the app id variables.

**Pull request merged**
