### PR TITLE
General Updates

### PR DESCRIPTION
**Pull request by devoidfury**
Fixes the following:
- #74 (use HTTPS for downloads)
- #65 (confusing error message) - strip leading 'v' from version if provided
- info: exit `build.bat` if `goxc` command not available
- formatting: use more native windows commands in `build.bat`
- formatting: use `go fmt` tool on all go files, and capitalize windows built-ins in `build.bat`
- fix: remove absolute path to your document folder in `nvm.iss` (probably want to double-check I didn't kill the installer build with this)

### CODE REVIEW

**Comment by devoidfury** [comment]
If the "go fmt" change is too much or unwanted, I'm happy to pull that out, just let me know.

**Comment by coreybutler** [comment]
I'm considering merging this... I am knee deep in the next version though & backlogged on some other work. Let me take a look at these and see if it's easier to cherry pick a few changes or merge the whole thing. Regardless, I want to thank you for taking the time to do this.

**Comment by devoidfury** [comment]
No worries, happy to help out (and thank you for putting the time into this tool, it's very helpful!). If there is anything I can do to make it easier, let me know.

**Comment by b-dur** [comment]
Hi @devoidfury 

I have started to look through all open PRs and see whether they still are relevant. Because of the age if this PR and the changes that have been made to the `master` I will close this PR.

If you still think that this PR is relevant, then you are more than welcome to reopen the PR.

**Pull request closed without merging**
