### PR TITLE
Add  Support for `nvm ls-remote` or `nvm list-remote` command

### PR DESCRIPTION
**Pull request by riazXrazor**
Add support for `nvm ls-remote` command which is available on the `nvm-sh/nvm` tool.
the command is used to have a look at a list of all node versions right from the terminal and select which one to install.

### CODE REVIEW

**Comment by riazXrazor** [comment]
Output looks something like this
image

**Comment by coreybutler** [comment]
I don't see the point of this when `nvm ls available` already exists:

image

**Comment by riazXrazor** [comment]
Oops i completely missed that in the command docs 🤦‍♂️, upon looking nicely i saw it now `nvm list [available] `

**Comment by riazXrazor** [comment]
@coreybutler  thanks for the quick feedback

**Pull request closed without merging**
