### PR TITLE
Fixes #41 - Issue with blank spaces in path

### LINKED ISSUE #41: Issue with blank spaces in path
Hello! I'm having a problem when i'm trying `nvm use <node_version>`
captura
Sorry for the spanish language in screenshot. It means "c:\Users\Edu" is not recognise as an internal command... bla bla bla.
My user name is "Edu Martin" and my path is "c:\Users\Edu Martin\AppData\Roaming\nvm"
Is it possible to be an error with black spaces in the path?? All settings in my app are standard

### PR DESCRIPTION
**Pull request by s-h-a-d-o-w**
exec.Command() can't handle spaces, even when quoted.
Command has to be modified using SysProcAttr.
See also:
https://github.com/golang/go/issues/15566

Plus: Minor refactoring - reordering of functions, more consistent capitalization, sorting of imports and whatnot.
Let me know if you don't appreciate this part. ;)

### CODE REVIEW

**Comment by coreybutler** [comment]
I know I'm way behind... wanted you to know I'm testing this, targeting inclusion the 1.1.8 release.

**Comment by s-h-a-d-o-w** [comment]
Cool, thanks for the update!

**Comment by coreybutler** [comment]
@s-h-a-d-o-w - Are you using different line endings? It looks like the entire file is being replaced instead of just your changes... I suspect a different type of line-ending. I'd like to see that cleaned up, then I'll merge this since it seems like it's fixing problems for several folks.

**Comment by s-h-a-d-o-w** [comment]
I have `core.autocrlf` set to `true`. Since I've never worked on a project with committed CRLFs and I doubt that I ever will again, could you please fix that? (I assume you're more familiar with this than me)
Might be a good idea to add a .gitattributes with `* text eol=crlf` to avoid something like this in the future.

**Comment by coreybutler** [comment]
@s-h-a-d-o-w I'm not sure how the line endings got screwed up in the first place, but I've taken your suggestion and added a `.gitattributes` file. I'm actually going to force line feeds instead of CRLF, which should be a more natural fit for most. I've also taken care of the existing issue and some of the resulting merge conflicts... so, all should be in order now.

Aside from fixing a longstanding issue, I was happy to see some of your other nice changes (which was also a stark reminder of how much of a go novice I was when I wrote some of that code!). Anyhow, this contribution was definitely needed and super-appreciated. There are a few other maintenance things I'll be adding to the project before the next release, but your work should show up then. Unless you object to it, I'll be listing your handle amongst the thank-you's in the `README`.

**Comment by s-h-a-d-o-w** [comment]
Thank you, it's always great to contribute to a project where one's work is appreciated!
I also appreciate the offer of adding my handle to the README would be nice - I'd like that.

(On a side note: Not sure how to say this because I don't want to take away from your efforts but instead express how happy I was but... I had actually never used Go before and was glad to be done in about 2 hours. Didn't find the experience too pleasant. I for one will stick with JS, C/C++, Python and Java for the time being. :wink: )

**Comment by coreybutler** [comment]
Haha - no worries. I considered using Java instead of Go, but it has been ages since I've done anything real with it. For me, Go is a bit like git was the first time.... took some getting used to, but then I was pretty happy with it. Simple cross-platform compilation was the big winner (and yes, that's a hint about the future of NVM4W).

**Comment by s-h-a-d-o-w** [comment]
Simple cross-platform, huh? Didn't know that about Go. I can see how that's appealing. Makes me think of Python (basically the only language I truly enjoy for its own sake - it's just so concise (mostly) and convenient...) - have mostly worked with that on Windows but it seems like its modules are platform-agnostic.
Anyway - all the best for that future. :wink:

**Comment by ctsstc** [comment]
Any chance of a pre-release for 1.1.8 @coreybutler excited for this fix : ) thanks @s-h-a-d-o-w

**Comment by s-h-a-d-o-w** [comment]
@ctsstc You could use the release from my fork until Corey releases 1.1.8.

**Comment by RobertDaleSmith** [comment]
@coreybutler could we get an updated release install including this bug fix?

**Comment by owenblacker** [comment]
+1 on the updated release, please? 😊

**Pull request merged**
