### PR TITLE
Update patch version

### PR DESCRIPTION
**Pull request by b-dur**
Updates variables from `1.1.6` to `1.1.7`

### CODE REVIEW

**Comment by b-dur** [comment]
@coreybutler gentle ping 😀

**Comment by loxy** [comment]
Is this project dead?

**Comment by b-dur** [comment]
No, it isn't. Just lacking resources, I guess you can call it.
I would welcome more contributors to the project.

**Comment by b-dur** [comment]
@coreybutler ping

**Comment by coreybutler** [comment]
Closing because a 1.1.7 release is coming tonight/tomorrow.

**Comment by loxy** [comment]
nvm version still shows version 1.1.5 after a fresh (uninstalled nvm before) install.

**Comment by coreybutler** [comment]
@loxy - open that as a new issue. I've heard one other person mention that... but I think it's related to the installer, not this patch.

**Comment by loxy** [comment]
Done, see: https://github.com/coreybutler/nvm-windows/issues/375

**Pull request closed without merging**
