### PR TITLE
Suppress remove prompt and force delete

### PR DESCRIPTION
**Pull request by nadirhamid**
Hello,

I do not know if this PR is helpful or not but I have been trying to use this on a Windows box recently and I have been getting some unpredictable results depending on how I have setup NodeJS prior to installing nvm-windows. 

Can you please explain: How NVM works when Node.js is already installed ?

For example I have tested in two scenarios. I have had some mixed results. Scenarios:

1. Install nvm-windows using official setup
By installing NVM on Windows  I have been able to install new Node.js versions. However with this approach I cannot see node being updated in my environemnt. I see the nodejs version in the NVM_HOME directory but not in my path.
2. Test nvm-windows directly using Go
I have tried to clone the source code and test it out locally. It all works fine but I am not able to see the "runElevated" call working all the time (see line 402 in nvm.go to be specific). The error I get is: exit status 145: The directory is not empty.

In my PR I have added the /S and /Q options to the the rmdir command. These options have helped me update my Windows environment (maybe there is another approach ?)

Again I do not know if this PR is helpful or not. If it is not helpful I would just like to know why these commands were not in the source code already. 

Is there a better approach to solving my problem ?

Thanks

### CODE REVIEW

**Comment by coreybutler** [comment]
NVM attempts to move prior installations of Node into a subdirectory of the nvm root, but it doesn't always work. It depends on how it was originally installed (official install, scoop, nuget, etc). Since NVM4W cannot guarantee a migration of the existing Node environment, it is recommended folks uninstall Node before installing NVM4W (as listed in the README). Most version managers have this requirement, since they don't have control over prior installations.

In scenario 1, updated versions of Node are installed within the nvm node directory. This is where the symlink (NVM_SYMLINK) looks for Node installations. The entire point of NVM4W is to _avoid_ changing anything in the `PATH`.

In scenario 2, the `/S` and `/Q` options will silence any errors. I tried not to use those so behavior would be predictable. If an error occurs, it should be displayed, not ignored.

I suspect you're getting the "directory not empty" error because the symlink is conflicting with a phyiscal directory at the same path (such as a previous installation of Node created before the install of NVM4W).

**Comment by nadirhamid** [comment]
@coreybutler 

"I suspect you're getting the "directory not empty" error because the symlink is conflicting with a phyiscal directory at the same path (such as a previous installation of Node created before the install of NVM4W)."

Yes this may have been the case. I have been able to solve the issue locally and it seems to be working fine now.

I will keep your comments in mind should I plan to use NVM in the future.

Great utility BTW, I will recommend it to all my peers who use node on Windows.

Thanks

**Comment by student1060632fpt** [comment]
If I already get this bug, please tell me the fast way to fix that please @nadirhamid and @coreybutler, thank you

**Comment by coreybutler** [comment]
@student1060632fpt - yes, if you have Node.js installed prior to installing NVM for Windows, the fastest way to remove it is using the Settings -> Apps menu to remove the original installation. The Node uninstaller _may_ remove the `PATH` for NVM for Windows, so you _may_ need to reinstall NVM for Windows as well. I'd suggest uninstalling Node, then trying NVM for Windows. If it doesn't work, reinstall NVM for Windows.

Closing since the OP found a solution.

**Pull request closed without merging**
