### PR TITLE
Add Winget Releaser workflow & Dependabot

### LINKED ISSUE #547: Feature Request: Package for Winget
Make sure you have reviewed the [common issues](https://github.com/coreybutler/nvm-windows/wiki/Common-Issues) and existing issues before submitting a new issue.

If this is a question about how to use NVM4W, please use [stackoverflow](http://stackoverflow.com/questions/tagged/nvm-windows) instead.

If this is an issue regarding antivirus, make sure you search the existing issues first.

### My Environment

- [ ] Windows 7 or below (not truly supported due to EOL - see wiki for details)
- [ ] Windows 8
- [ ] Windows 8.1
- [ ] Windows 10
- [ ] Windows 10 IoT Core
- [ ] Windows Server 2012
- [ ] Windows Server 2012 R2
- [ ] Windows Server 2016

- [ ] My Windows installation is non-English.

### I'm using NVM4W version: Current

Run `nvm version` if you don't know.

### I have already...

- [ Y] read the README to be aware of npm gotchas & antivirus issues.
- [ Y] reviewed the [wiki](https://github.com/coreybutler/nvm-windows/wiki) to make sure my issue hasn't already been resolved.
- [ Y] verified I'm using an account with administrative privileges.
- [ Y] searched the issues (open and closed) to make sure this isn't a duplicate.
- [ Y] made sure this isn't a question about how to use NVM for Windows, since [gitter](https://gitter.im/coreybutler/nvm-windows?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) is used for questions and comments.

### My issue is related to (check only those which apply):

- [ ] settings.txt
- [ ] proxy support (Have you tried version 1.1.0+?)
- [ ] 32 or 64 bit support (Have you tried version 1.1.3+?)
- [ ] Character escaping (Have you tried version 1.1.6+?)
- [ X] A standard shell environment (terminal/powershell)
- [ ] A non-standard shell environment (Cmder, Hyper, Cygwin, git)

### Expected Behavior

winget install nvm-windows (Add Packaging to the nvm-windows project and submit for acceptance.)

I am willing to give this a first stab in a branch if you want. Or you can have a current project member do it.

### Actual Behavior

N/A

### Steps to reproduce the problem:

N/A

### PR DESCRIPTION
**Pull request by sitiom**
This action automatically generates manifests for the Winget Community Repository ([microsoft/winget-pkgs](https://github.com/microsoft/winget-pkgs)).

nvm-windows in Winget is outdated, and I have manually updated it for now (https://github.com/microsoft/winget-pkgs/pull/89203). But once this is merged, automatic updates should automatically be deployed when you release a new version.

**Before merging this:**
1. Add a PAT with `public_repo` scope as a repository secret named `WINGET_TOKEN` (or rename the secret name in the workflow).

example

2. Fork https://github.com/microsoft/winget-pkgs under @coreybutler . The action will use that fork for making a branch and creating a PR with the upstream [winget-pkgs](https://github.com/microsoft/winget-pkgs) repository on every release.
3. Install [Pull](https://github.com/apps/pull) on the winget-pkgs fork to ensure that it is constantly updated.

The documentation and source code of the action is available [here](https://github.com/vedantmgoyal2009/winget-releaser/).

If you want to see an example of a PR created using this action, see [microsoft/winget-pkgs/pulls (Pull request has been automatically created using 🛫 WinGet Releaser)](https://github.com/microsoft/winget-pkgs/pulls?q=is%3Apr+sort%3Aupdated-desc+Pull+request+has+been+automatically+created+using+%F0%9F%9B%AB+WinGet+Releaser).

- Resolves #547

### CODE REVIEW

**Review by veleek — APPROVED** [review]
Was _just_ about to look into something like this!

**Comment by sitiom** [comment]
@coreybutler Bump

**Review by coreybutler — APPROVED** [review]

**Comment by coreybutler** [comment]
Alright, we're going to give this a shot. There will be a new minor release sometime in the next week, so we'll see how it goes.

**Comment by sitiom** [comment]
@coreybutler Can you rerun the failed workflow in https://github.com/coreybutler/nvm-windows/actions/runs/4685243965/jobs/8302161400?

**Comment by sitiom** [comment]
@coreybutler Can you rerun the failed workflow in https://github.com/coreybutler/nvm-windows/actions/runs/4685243965/jobs/8302161400?

Edit: Nevermind. `nvm-setup.exe` doesn't exist. Please add that first then rerun the workflow.

**Comment by coreybutler** [comment]
@sitiom I think the action ran before the assets were fully uploaded. `nvm-setup.exe` was included when I cut the release. However; it looks like the process is expecting a URL. I don't know where this would be configured or what the value should be. https://github.com/coreybutler/nvm-windows/actions/runs/4685243965/jobs/8302254488#step:2:93

**Comment by sitiom** [comment]
> @sitiom I think the action ran before the assets were fully uploaded. `nvm-setup.exe` was included when I cut the release.

This is the case. However, I still don't see the `nvm-setup.exe` asset in the releases. Was it really included?

https://github.com/coreybutler/nvm-windows/releases/tag/1.1.11

**Comment by coreybutler** [comment]
@sitiom - my mistake, I read that as nvm-setup.**zip**, which does exist.

**Comment by sitiom** [comment]
Can you try to rerun the workflow again? The latest error is unusual 🤔. Maybe the token is invalid?

**Comment by sitiom** [comment]
@russellbanks Any ideas? https://github.com/coreybutler/nvm-windows/actions/runs/4685243965/jobs/8313882263

**Comment by sitiom** [comment]
I have manually created the PR, and there was a SmartScreen error? https://github.com/microsoft/winget-pkgs/pull/102565#issuecomment-1509508867

**Comment by coreybutler** [comment]
@sitiom The URL it is complaining about only exists in the README of the repo, for a "sponsor" (which happens to be one of my firms). I know the link is valid, but I'm not sure why the README would be picked up at all.

**Comment by sitiom** [comment]
I think it took the first link from your [GitHub profile](https://github.com/coreybutler) as the `PublisherUrl`.

**Comment by cfreear** [comment]
> I think it took the first link from your [GitHub profile](https://github.com/coreybutler) as the `PublisherUrl`.

This is it, the tool that the github action uses takes the "website" field from your github profile and uses it as the publisher URL :/

https://github.com/russellbanks/Komac/blob/2d92db680c29ee43a2a6c085d8a34ec36dd736c4/src/main/kotlin/detection/github/GitHubDetection.kt#L62

**Comment by coreybutler** [comment]
Well that's annoying. Metadoc (the linked page) is one of my other ventures, unrelated to NVM4W.

**Comment by cfreear** [comment]
Komac (the tool used by this action) now prioritises the repo homepage over the owner's website field for the publisher url, adding the repo page url (https://github.com/coreybutler/nvm-windows) to the about section might now fix this.

**Comment by rickgoemans** [comment]
Any progress on this? Winget still has `1.1.10` instead of `1.1.12`

**Comment by sitiom** [comment]
> Any progress on this? Winget still has `1.1.10` instead of `1.1.12`

https://github.com/coreybutler/nvm-windows/discussions/1066#discussioncomment-7647667

**Pull request merged**
