### PR TITLE
add support for nvm current

### PR DESCRIPTION
**Pull request by riazXrazor**
certain terminal use it to detect the version of node like https://github.com/denysdovhan/spaceship-prompt

### CODE REVIEW

**Comment by riazXrazor** [comment]
anybody looking into it

**Comment by riazXrazor** [comment]
@coreybutler anything ?

**Comment by djm158** [comment]
@riazXrazor I'm not a contributor here, but this seems difficult to review due to all the formatting changes? Is it possible to reupload this PR so that the diff is just the code changes?

**Comment by riazXrazor** [comment]
@djm158 thanks got it, let me see if i can fix that up

**Comment by riazXrazor** [comment]
https://github.com/coreybutler/nvm-windows/pull/569/commits/40ae5103ea55d8331604033787c21f378d9ad294
did a clean PR with jst the update had to disable autoformatting i hope its clear now

**Review by djm158 — APPROVED** [review]

**Comment by djm158** [comment]
LGTM guess we just need approval from @coreybutler

**Comment by riazXrazor** [comment]
@djm158 u can comment on the new PR (https://github.com/coreybutler/nvm-windows/pull/569) this one discard it

**Comment by wesleycoder** [comment]
I've gone through the same scenario of installing spaceship on windows and getting the annoying help output of nvm-windows because of this missing command.

I would love to see this PR merged if no objections are found.
Is there anyone that could move this issue and PR forward?

**Comment by riazXrazor** [comment]
@coreybutler merge plz if its ok

**Comment by coreybutler** [comment]
Closing because this was merged in another PR.

**Pull request closed without merging**
