### PR TITLE
Fixed for node v4

### LINKED ISSUE #85: Can't install nodejs v4
I got this error when I try to install the version 4.0.
node_nvm_4

I have this problem on **windows 8 and 10**. Any suggestions? Thanks!

### PR DESCRIPTION
**Pull request by sullivanpt**
New PR for node v4 support. This builds on PR #92 but fixes compile and run time errors. Also Fixes errors in PR #77. 

And fixes the 'nvm install latest' command which was failing because the version available check was checking against the string "latest".

In my limited testing this version seems to build and run correctly, as tested against v0.10.40 and v4.1.0.

Fixes #85

### CODE REVIEW

**Comment by coreybutler** [comment]
My tests passed, thanks for the contribution!

**Comment by alexbooker** [comment]
Awesome work, @sullivanpt!

**Comment by sullivanpt** [comment]
Thanks, but the bulk of the credit for this PR goes to @rainabba

**Comment by coreybutler** [comment]
@sullivanpt - that's why I thanked you both in the README :)

**Comment by alexbooker** [comment]
@sullivanpt @rainabba In which case, good work, all!

**Pull request merged**
